import XCTest
@testable import BeautifulMermaid
import Foundation

final class AsciiVisualReportGenerator: XCTestCase {

    struct TestDiagram: Codable {
        let id: String
        let category: String
        let name: String
        let source: String
        let options: [String: Bool]?
    }

    struct TestDiagrams: Codable {
        let diagrams: [TestDiagram]
    }

    struct TsReference: Codable {
        let plain: String
        let html: String
        let error: String?
    }

    struct Row {
        let diagram: TestDiagram
        let swiftPlain: String?
        let swiftHtml: String?
        let tsPlain: String?
        let tsHtml: String?
        let match: Bool
        let swiftError: String?
        let tsError: String?
    }

    /// Renders all diagrams to ASCII (Swift) and loads TS reference,
    /// then generates a side-by-side HTML comparison report.
    func testGenerateAsciiVisualReport() throws {
        let cwd = FileManager.default.currentDirectoryPath
        let root = (cwd as NSString).deletingLastPathComponent

        let diagramsPath = (root as NSString).appendingPathComponent("verification/shared/test-diagrams.json")
        guard FileManager.default.fileExists(atPath: diagramsPath) else {
            // These exporters regenerate comparison artefacts from a fixture that lives
            // outside the package (the original monorepo layout). Absent it, there is
            // nothing to export -- that is not a failure, so skip rather than fail.
            throw XCTSkip("Missing verification input: \(diagramsPath)")
        }

        let data = try Data(contentsOf: URL(fileURLWithPath: diagramsPath))
        let testDiagrams = try JSONDecoder().decode(TestDiagrams.self, from: data)

        let outputDir = (root as NSString).appendingPathComponent("verification/output/ascii")
        try FileManager.default.createDirectory(atPath: outputDir, withIntermediateDirectories: true)

        // Load TS reference (generated by: bun run verification/tools/generate-ts-ascii.ts)
        let tsRefPath = (outputDir as NSString).appendingPathComponent("ts-ascii-reference.json")
        var tsRefs: [String: TsReference] = [:]
        if FileManager.default.fileExists(atPath: tsRefPath) {
            let tsData = try Data(contentsOf: URL(fileURLWithPath: tsRefPath))
            tsRefs = try JSONDecoder().decode([String: TsReference].self, from: tsData)
            print("Loaded \(tsRefs.count) TS reference diagrams")
        } else {
            print("WARNING: No TS reference found at \(tsRefPath)")
            print("Run: bun run verification/tools/generate-ts-ascii.ts")
        }

        var rows: [Row] = []

        for diagram in testDiagrams.diagrams {
            print("=== ASCII RENDERING \(diagram.id) ===")

            var swiftPlain: String? = nil
            var swiftHtml: String? = nil
            var swiftError: String? = nil

            do {
                swiftPlain = try original_src_ascii_index.renderMermaidASCII(
                    diagram.source,
                    options: .init(colorMode: .explicit(.none))
                )
                swiftHtml = try original_src_ascii_index.renderMermaidASCII(
                    diagram.source,
                    options: .init(colorMode: .explicit(.html))
                )
            } catch {
                swiftError = error.localizedDescription
                fputs("FAIL [\(diagram.id)]: \(error)\n", stderr)
            }

            let tsRef = tsRefs[diagram.id]
            let tsPlain = tsRef?.plain
            let tsHtml = tsRef?.html
            let tsError = tsRef?.error

            let match = swiftPlain != nil && tsPlain != nil && swiftPlain == tsPlain

            rows.append(Row(
                diagram: diagram,
                swiftPlain: swiftPlain,
                swiftHtml: swiftHtml,
                tsPlain: tsPlain,
                tsHtml: tsHtml,
                match: match,
                swiftError: swiftError,
                tsError: tsError
            ))
        }

        // Generate HTML report
        let htmlPath = (outputDir as NSString).appendingPathComponent("ascii-comparison.html")
        let html = generateComparisonHtml(rows: rows)
        try html.write(toFile: htmlPath, atomically: true, encoding: .utf8)

        let matchCount = rows.filter { $0.match }.count
        let mismatchCount = rows.filter { !$0.match && $0.swiftPlain != nil && $0.tsPlain != nil }.count
        let swiftFailCount = rows.filter { $0.swiftError != nil }.count
        print("\n=== ASCII Comparison Report Generated ===")
        print("HTML:      \(htmlPath)")
        print("Total:     \(rows.count) diagrams")
        print("Match:     \(matchCount)")
        print("Mismatch:  \(mismatchCount)")
        print("Swift err: \(swiftFailCount)")
        print("No TS ref: \(rows.filter { $0.tsPlain == nil }.count)")
    }

    // MARK: - HTML Report

    private func generateComparisonHtml(rows: [Row]) -> String {
        let matchCount = rows.filter { $0.match }.count
        let mismatchCount = rows.filter { !$0.match && $0.swiftPlain != nil && $0.tsPlain != nil }.count
        let errorCount = rows.filter { $0.swiftError != nil }.count

        // Group by category
        var categories: [(name: String, items: [Row])] = []
        var seen: [String: Int] = [:]
        for r in rows {
            if let idx = seen[r.diagram.category] {
                categories[idx].items.append(r)
            } else {
                seen[r.diagram.category] = categories.count
                categories.append((r.diagram.category, [r]))
            }
        }

        var html = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ASCII Comparison: TypeScript vs Swift</title>
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8f9fa; color: #1a1a2e; padding: 20px; }
            h1 { margin-bottom: 8px; color: #111; }
            .summary { margin-bottom: 24px; padding: 16px; background: #fff; border-radius: 8px; border: 1px solid #e0e0e0; }
            .summary .match { color: #16a34a; font-weight: 600; }
            .summary .mismatch { color: #d97706; font-weight: 600; }
            .summary .fail { color: #dc2626; font-weight: 600; }
            .category { margin-bottom: 32px; }
            .category h2 { margin-bottom: 12px; text-transform: capitalize; border-bottom: 2px solid #e0e0e0; padding-bottom: 4px; color: #333; }
            .filter-bar { margin-bottom: 16px; display: flex; gap: 8px; }
            .filter-btn { padding: 6px 14px; font-size: 13px; cursor: pointer; background: #fff; color: #555; border: 1px solid #d0d0d0; border-radius: 6px; }
            .filter-btn.active { background: #3b82f6; color: white; border-color: #3b82f6; }
            .row { margin-bottom: 16px; background: #fff; border-radius: 8px; border: 1px solid #e0e0e0; overflow: hidden; }
            .row.match { border-left: 4px solid #16a34a; }
            .row.mismatch { border-left: 4px solid #d97706; }
            .row.error { border-left: 4px solid #dc2626; }
            .row-header { padding: 10px 14px; border-bottom: 1px solid #e0e0e0; display: flex; justify-content: space-between; align-items: center; }
            .row-header .name { font-weight: 600; font-size: 14px; }
            .row-header .id { font-size: 12px; color: #888; font-family: monospace; }
            .badge { font-size: 11px; padding: 2px 8px; border-radius: 4px; font-weight: 600; }
            .badge.match { background: #dcfce7; color: #16a34a; }
            .badge.mismatch { background: #fef3c7; color: #d97706; }
            .badge.fail { background: #fee2e2; color: #dc2626; }
            .columns { display: grid; grid-template-columns: 1fr 1fr; }
            .col { border-right: 1px solid #e0e0e0; }
            .col:last-child { border-right: none; }
            .col-header { padding: 6px 14px; background: #f0f1f3; font-size: 12px; font-weight: 600; color: #666; text-transform: uppercase; letter-spacing: 0.05em; }
            .ascii-output {
                font-family: 'SF Mono', 'Menlo', 'Monaco', 'Courier New', monospace;
                font-size: 11px;
                line-height: 1.35;
                background: #fff;
                color: #1a1a2e;
                padding: 10px 12px;
                overflow-x: auto;
                white-space: pre;
                min-height: 60px;
                max-height: 500px;
                overflow-y: auto;
            }
            .error-msg { color: #dc2626; font-size: 12px; padding: 10px 12px; }
            .empty-msg { color: #999; font-size: 12px; padding: 10px 12px; font-style: italic; }
            .source-toggle { font-size: 12px; color: #3b82f6; cursor: pointer; padding: 6px 14px; display: inline-block; }
            .source-code { display: none; font-family: monospace; font-size: 11px; background: #f5f5f5; color: #555; padding: 8px 14px; white-space: pre-wrap; word-break: break-all; max-height: 150px; overflow-y: auto; border-top: 1px solid #e0e0e0; }
        </style>
        </head>
        <body>
        <h1>ASCII Comparison: TypeScript vs Swift</h1>
        <div class="summary">
            <p>Generated: <strong>\(ISO8601DateFormatter().string(from: Date()))</strong></p>
            <p>Total: <strong>\(rows.count)</strong> &nbsp;|&nbsp;
               <span class="match">Match: \(matchCount)</span> &nbsp;|&nbsp;
               <span class="mismatch">Mismatch: \(mismatchCount)</span> &nbsp;|&nbsp;
               <span class="fail">Errors: \(errorCount)</span></p>
        </div>
        <div class="filter-bar">
            <button class="filter-btn active" onclick="filterRows('all')">All</button>
            <button class="filter-btn" onclick="filterRows('match')">Match</button>
            <button class="filter-btn" onclick="filterRows('mismatch')">Mismatch</button>
            <button class="filter-btn" onclick="filterRows('error')">Errors</button>
        </div>
        """

        for cat in categories {
            html += """
            <div class="category">
            <h2>\(cat.name) (\(cat.items.count))</h2>
            """
            for (i, r) in cat.items.enumerated() {
                let uniqueId = "\(r.diagram.category)-\(i)"
                let status: String
                let badgeLabel: String
                if r.swiftError != nil {
                    status = "error"
                    badgeLabel = "ERROR"
                } else if r.tsPlain == nil {
                    status = "mismatch"
                    badgeLabel = "NO REF"
                } else if r.match {
                    status = "match"
                    badgeLabel = "MATCH"
                } else {
                    status = "mismatch"
                    badgeLabel = "DIFF"
                }

                html += """
                <div class="row \(status)" data-status="\(status)">
                  <div class="row-header">
                    <div>
                      <span class="name">\(escapeHtml(r.diagram.name))</span>
                      <span class="id">\(r.diagram.id)</span>
                    </div>
                    <span class="badge \(status)">\(badgeLabel)</span>
                  </div>
                  <div class="columns">
                    <div class="col">
                      <div class="col-header">TypeScript (reference)</div>
                """

                if let tsErr = r.tsError, !tsErr.isEmpty {
                    html += "<div class=\"error-msg\">\(escapeHtml(tsErr))</div>"
                } else if let tsHtml = r.tsHtml, !tsHtml.isEmpty {
                    html += "<div class=\"ascii-output\">\(tsHtml)</div>"
                } else if let tsPlain = r.tsPlain, !tsPlain.isEmpty {
                    html += "<div class=\"ascii-output\">\(escapeHtml(tsPlain))</div>"
                } else {
                    html += "<div class=\"empty-msg\">No TS reference available</div>"
                }

                html += """
                    </div>
                    <div class="col">
                      <div class="col-header">Swift</div>
                """

                if let swiftErr = r.swiftError {
                    html += "<div class=\"error-msg\">\(escapeHtml(swiftErr))</div>"
                } else if let swiftHtml = r.swiftHtml, !swiftHtml.isEmpty {
                    html += "<div class=\"ascii-output\">\(swiftHtml)</div>"
                } else if let swiftPlain = r.swiftPlain {
                    html += "<div class=\"ascii-output\">\(escapeHtml(swiftPlain))</div>"
                } else {
                    html += "<div class=\"empty-msg\">Render failed</div>"
                }

                html += """
                    </div>
                  </div>
                  <span class="source-toggle" onclick="document.getElementById('src-\(uniqueId)').style.display=document.getElementById('src-\(uniqueId)').style.display==='block'?'none':'block'">Show source</span>
                  <div class="source-code" id="src-\(uniqueId)">\(escapeHtml(r.diagram.source))</div>
                </div>
                """
            }
            html += "</div>\n"
        }

        html += """
        <script>
        function filterRows(status) {
            document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
            event.target.classList.add('active');
            document.querySelectorAll('.row').forEach(row => {
                if (status === 'all' || row.dataset.status === status) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        }
        </script>
        </body></html>
        """
        return html
    }

    private func escapeHtml(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
         .replacingOccurrences(of: "<", with: "&lt;")
         .replacingOccurrences(of: ">", with: "&gt;")
         .replacingOccurrences(of: "\"", with: "&quot;")
    }
}
